services:
  frontend:
    build:
      context: ../wsd-frontend
      dockerfile: ../wsd-frontend/Dockerfile
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        NEXT_PUBLIC_WSD__DEBUG: ${NEXT_PUBLIC_WSD__DEBUG}
        NEXT_PUBLIC_WSD__PROTOCOL: ${NEXT_PUBLIC_WSD__PROTOCOL}
        NEXT_PUBLIC_WSD__NAME: ${NEXT_PUBLIC_WSD__NAME}
        NEXT_PUBLIC_WSD__MOTTO: ${NEXT_PUBLIC_WSD__MOTTO}
        NEXT_PUBLIC_WSD__DOMAIN: ${NEXT_PUBLIC_WSD__DOMAIN}
        NEXT_PUBLIC_WSD__API__BASE_URL: ${NEXT_PUBLIC_WSD__API__BASE_URL}
        NEXT_PUBLIC_WSD__API__AUTH_BASE_URL: ${NEXT_PUBLIC_WSD__API__AUTH_BASE_URL}
        NEXT_PUBLIC_WSD__LANGUAGE: ${NEXT_PUBLIC_WSD__LANGUAGE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__DSN: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__DSN}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__TRACES_SAMPLE_RATE: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__TRACES_SAMPLE_RATE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_SESSION_SAMPLE_RATE: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_SESSION_SAMPLE_RATE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_ON_ERROR_SAMPLE_RATE: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_ON_ERROR_SAMPLE_RATE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__GOOGLE_ANALYTICS__GA_ID: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__GOOGLE_ANALYTICS__GA_ID}
        NEXT_PUBLIC_WSD__VERIFICATION__MICROSOFT__ASSOCIATED_APPLICATION_ID: ${NEXT_PUBLIC_WSD__VERIFICATION__MICROSOFT__ASSOCIATED_APPLICATION_ID}
        NEXT_PUBLIC_WSD__GITHUB_LINK: ${NEXT_PUBLIC_WSD__GITHUB_LINK}
    env_file: ../../.env
    networks:
      - internal
      - external
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
