# Generated by Django 5.1.3 on 2025-04-04 15:44

import apps.core.managers.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.core.managers.user.UserManager()),
            ],
        ),
    ]
