# Generated by Django 5.1.3 on 2025-04-24 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_username_alter_userevent_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. It must start with a lowercase letter and contain only lowercase letters, digits, or underscores.",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid username. It must start with a lowercase letter and contain only lowercase letters, digits, or underscores.",
                        regex="^[a-z][a-z0-9_]*\\Z",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. It must start with a lowercase letter and contain only lowercase letters, digits, or underscores.",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid username. It must start with a lowercase letter and contain only lowercase letters, digits, or underscores.",
                        regex="^[a-z][a-z0-9_]*\\Z",
                    )
                ],
            ),
        ),
    ]
