# Generated by Django 5.1.3 on 2025-04-27 03:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_username_alter_userevent_username"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's avatar image.",
                null=True,
                upload_to="avatars",
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's avatar image.",
                null=True,
                upload_to="avatars",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "user_userevent" ("avatar", "created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at", "username") VALUES (NEW."avatar", NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug", NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="4a717c606e36701b7f1f15bbcb7f3da3f6d76bf6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_12d49",
                    table="user_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "user_userevent" ("avatar", "created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at", "username") VALUES (NEW."avatar", NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug", NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="3af9eaab61d55a6a727f3cca3ed00fe8bd86a19a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_5b09f",
                    table="user_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "user_userevent" ("avatar", "created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at", "username") VALUES (OLD."avatar", OLD."created_at", OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."slug", OLD."updated_at", OLD."username"); RETURN NULL;',
                    hash="cc6eb860d31ff655e554134cbad3d9715453dc0e",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_dbcd9",
                    table="user_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
