# Generated by Django 5.1.3 on 2025-05-13 18:39

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_insert_insert_remove_user_update_update_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="user",
            name="card_style",
            field=models.CharField(
                choices=[
                    ("RELAXED", "Relaxed"),
                    ("NORMAL", "Normal"),
                    ("COMPACT", "Compact"),
                ],
                default="NORMAL",
                help_text="User's card style.",
                max_length=7,
                verbose_name="Card Style",
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="card_style",
            field=models.CharField(
                choices=[
                    ("RELAXED", "Relaxed"),
                    ("NORMAL", "Normal"),
                    ("COMPACT", "Compact"),
                ],
                default="NORMAL",
                help_text="User's card style.",
                max_length=7,
                verbose_name="Card Style",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "user_userevent" ("avatar", "card_style", "created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at", "username") VALUES (NEW."avatar", NEW."card_style", NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug", NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="73e3195896b09b85f9400e1a18f4379a63165af8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_12d49",
                    table="user_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "user_userevent" ("avatar", "card_style", "created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at", "username") VALUES (NEW."avatar", NEW."card_style", NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug", NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="1392404d9845500d07aad120321e0d3223115158",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_5b09f",
                    table="user_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "user_userevent" ("avatar", "card_style", "created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at", "username") VALUES (OLD."avatar", OLD."card_style", OLD."created_at", OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."slug", OLD."updated_at", OLD."username"); RETURN NULL;',
                    hash="ee77074e4fd6126c3c3e003d3567d819123def62",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_dbcd9",
                    table="user_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
