/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': { get: { parameters: { query: '' } } }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: { '': '' }
}

export type $defs = Record<string, never>

export interface operations {
  '/': { '': '' }
}
