# Generated by Django 5.1.3 on 2025-03-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.CharField(
                help_text="Name of the category.",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
