# Generated by Django 5.1.3 on 2025-03-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_post_insert_insert_remove_post_update_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Post Tags related to Post",
                related_name="posts",
                through="core.PostObjectTag",
                to="core.posttag",
                verbose_name="Post Tags",
            ),
        ),
    ]
