# Generated by Django 5.1.3 on 2025-04-28 19:10

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_notification_notificationevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="postcomment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="postcomment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="postcomment",
            name="delete_delete",
        ),
        migrations.RenameField(
            model_name="postcomment",
            old_name="body",
            new_name="body_text",
        ),
        migrations.RenameField(
            model_name="postcommentevent",
            old_name="body",
            new_name="body_text",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="postcomment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_postcommentevent" ("body_text", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "slug", "updated_at", "user_id") VALUES (NEW."body_text", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."post_id", NEW."slug", NEW."updated_at", NEW."user_id"); RETURN NULL;',
                    hash="14ab13d7dc5fa8634670b8b91b3c358917f05a4b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_f06eb",
                    table="core_postcomment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="postcomment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_postcommentevent" ("body_text", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "slug", "updated_at", "user_id") VALUES (NEW."body_text", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."post_id", NEW."slug", NEW."updated_at", NEW."user_id"); RETURN NULL;',
                    hash="9f5ac89db1433f0895c208f6a88c7cb1fbcaf8c1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_97b3a",
                    table="core_postcomment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="postcomment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_postcommentevent" ("body_text", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "slug", "updated_at", "user_id") VALUES (OLD."body_text", OLD."created_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."post_id", OLD."slug", OLD."updated_at", OLD."user_id"); RETURN NULL;',
                    hash="ca286da186efb6118baa2225e59ca25f4104ef0d",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_2ffd1",
                    table="core_postcomment",
                    when="AFTER",
                ),
            ),
        ),
    ]
