# Generated by Django 5.1.3 on 2025-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_postcomment_insert_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="body_text",
            field=models.TextField(help_text="The actual comment as text.", verbose_name="Body Text"),
        ),
        migrations.AlterField(
            model_name="postcommentevent",
            name="body_text",
            field=models.TextField(help_text="The actual comment as text.", verbose_name="Body Text"),
        ),
    ]
