# Generated by Django 5.1.3 on 2025-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_move_old_comment_body_to_json_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="body_text",
            field=models.TextField(
                blank=True,
                help_text="The actual comment as text.",
                null=True,
                verbose_name="Body Text",
            ),
        ),
        migrations.AlterField(
            model_name="postcommentevent",
            name="body_text",
            field=models.TextField(
                blank=True,
                help_text="The actual comment as text.",
                null=True,
                verbose_name="Body Text",
            ),
        ),
    ]
