# Generated by Django 5.1.3 on 2025-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_postcomment_body_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("LIKE", "Like"),
                    ("COMMENT", "Comment"),
                    ("COMMENT_MENTION", "Comment Mention"),
                ],
                help_text="Event Type",
                max_length=15,
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("LIKE", "Like"),
                    ("COMMENT", "Comment"),
                    ("COMMENT_MENTION", "Comment Mention"),
                ],
                help_text="Event Type",
                max_length=15,
                verbose_name="Event",
            ),
        ),
    ]
