# Generated by Django 5.1.3 on 2025-04-29 05:48

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_notification_event_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="postcomment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="postcomment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="postcomment",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="postcomment",
            name="body_text",
        ),
        migrations.RemoveField(
            model_name="postcommentevent",
            name="body_text",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="postcomment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_postcommentevent" ("body", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "slug", "updated_at", "user_id") VALUES (NEW."body", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."post_id", NEW."slug", NEW."updated_at", NEW."user_id"); RETURN NULL;',
                    hash="30d96ac9dc5d7f06f745dc592f65cbd37311b4c0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_f06eb",
                    table="core_postcomment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="postcomment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_postcommentevent" ("body", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "slug", "updated_at", "user_id") VALUES (NEW."body", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."post_id", NEW."slug", NEW."updated_at", NEW."user_id"); RETURN NULL;',
                    hash="339f50ed309ef90533bd6ae9c50d5945ef19bf90",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_97b3a",
                    table="core_postcomment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="postcomment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_postcommentevent" ("body", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "slug", "updated_at", "user_id") VALUES (OLD."body", OLD."created_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."post_id", OLD."slug", OLD."updated_at", OLD."user_id"); RETURN NULL;',
                    hash="a9af349184d50bd8f1465a068d0501c0624f3c79",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_2ffd1",
                    table="core_postcomment",
                    when="AFTER",
                ),
            ),
        ),
    ]
